### PR TITLE
Changing to a non-realtime thread in the sensor backend

### LINKED ISSUE #40: SensorBackend should use non-real-time thread
To my understanding, the cameras will anyway not work in real time, so there is probably no use of running the `SensorBackend` in a real-time thread. On the other hand, it is probably beneficial to keep the number of real-time threads low, so it would be better to use a standard non-real-time thread here.

https://github.com/open-dynamic-robot-initiative/robot_interfaces/blob/1fa5daa15c99d2a47e7d9f106e33bd8011d54127/include/robot_interfaces/sensors/sensor_backend.hpp#L49

### PR DESCRIPTION
**Pull request by shrutij01**
## Description

Earlier, the sensor backend was creating a realtime thread for the loop getting observations through the sensor driver and appending these to the sensor data. But as this anyway does not run in realtime, a non-realtime thread is used now. 

This fixes #40.

## How I Tested

Through the demo_camera

- [x] All new code is formatted according to our style guide (for C++ run clang-format, for Python, run flake8 and fix all warnings).
- [x] All new functions/classes are documented and existing documentation is updated according to changes.
- [x] No commented code from testing/debugging is kept (unless there is a good reason to keep it).

### CODE REVIEW

File: include/robot_interfaces/sensors/sensor_backend.hpp [hunk 1]
```diff
@@ -11,6 +11,7 @@
 #include <algorithm>
 #include <cmath>
 #include <cstdint>
+#include <thread>
 
 #include <real_time_tools/process_manager.hpp>
 #include <real_time_tools/thread.hpp>
```
Comment (luator) [inline include/robot_interfaces/sensors/sensor_backend.hpp]: these includes can now be removed.
